// Code generated by protoc-gen-go. DO NOT EDIT.
// source: p4/config/v1/p4types.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// These P4 types (struct, header_type, header_union and enum) are guaranteed to
// have a fully-qualified name (e.g. you cannot use an anonymous struct to
// declare a variable like in C). Instead of duplicating the type spec for these
// every time the type is used, we include the type spec once in this P4TypeInfo
// message and refer to the types by name in the P4DataTypeSpec message. We also
// support annotations for these type specs which can be useful, e.g. to
// identify well-known headers (such as ipv4).
type P4TypeInfo struct {
	Structs              map[string]*P4StructTypeSpec           `protobuf:"bytes,1,rep,name=structs,proto3" json:"structs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Headers              map[string]*P4HeaderTypeSpec           `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	HeaderUnions         map[string]*P4HeaderUnionTypeSpec      `protobuf:"bytes,3,rep,name=header_unions,json=headerUnions,proto3" json:"header_unions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Enums                map[string]*P4EnumTypeSpec             `protobuf:"bytes,4,rep,name=enums,proto3" json:"enums,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Error                *P4ErrorTypeSpec                       `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	SerializableEnums    map[string]*P4SerializableEnumTypeSpec `protobuf:"bytes,6,rep,name=serializable_enums,json=serializableEnums,proto3" json:"serializable_enums,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	NewTypes             map[string]*P4NewTypeSpec              `protobuf:"bytes,7,rep,name=new_types,json=newTypes,proto3" json:"new_types,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *P4TypeInfo) Reset()         { *m = P4TypeInfo{} }
func (m *P4TypeInfo) String() string { return proto.CompactTextString(m) }
func (*P4TypeInfo) ProtoMessage()    {}
func (*P4TypeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{0}
}

func (m *P4TypeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4TypeInfo.Unmarshal(m, b)
}
func (m *P4TypeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4TypeInfo.Marshal(b, m, deterministic)
}
func (m *P4TypeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4TypeInfo.Merge(m, src)
}
func (m *P4TypeInfo) XXX_Size() int {
	return xxx_messageInfo_P4TypeInfo.Size(m)
}
func (m *P4TypeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_P4TypeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_P4TypeInfo proto.InternalMessageInfo

func (m *P4TypeInfo) GetStructs() map[string]*P4StructTypeSpec {
	if m != nil {
		return m.Structs
	}
	return nil
}

func (m *P4TypeInfo) GetHeaders() map[string]*P4HeaderTypeSpec {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *P4TypeInfo) GetHeaderUnions() map[string]*P4HeaderUnionTypeSpec {
	if m != nil {
		return m.HeaderUnions
	}
	return nil
}

func (m *P4TypeInfo) GetEnums() map[string]*P4EnumTypeSpec {
	if m != nil {
		return m.Enums
	}
	return nil
}

func (m *P4TypeInfo) GetError() *P4ErrorTypeSpec {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *P4TypeInfo) GetSerializableEnums() map[string]*P4SerializableEnumTypeSpec {
	if m != nil {
		return m.SerializableEnums
	}
	return nil
}

func (m *P4TypeInfo) GetNewTypes() map[string]*P4NewTypeSpec {
	if m != nil {
		return m.NewTypes
	}
	return nil
}

// Describes a P4_16 type.
type P4DataTypeSpec struct {
	// Types that are valid to be assigned to TypeSpec:
	//	*P4DataTypeSpec_Bitstring
	//	*P4DataTypeSpec_Bool
	//	*P4DataTypeSpec_Tuple
	//	*P4DataTypeSpec_Struct
	//	*P4DataTypeSpec_Header
	//	*P4DataTypeSpec_HeaderUnion
	//	*P4DataTypeSpec_HeaderStack
	//	*P4DataTypeSpec_HeaderUnionStack
	//	*P4DataTypeSpec_Enum
	//	*P4DataTypeSpec_Error
	//	*P4DataTypeSpec_SerializableEnum
	//	*P4DataTypeSpec_NewType
	TypeSpec             isP4DataTypeSpec_TypeSpec `protobuf_oneof:"type_spec"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *P4DataTypeSpec) Reset()         { *m = P4DataTypeSpec{} }
func (m *P4DataTypeSpec) String() string { return proto.CompactTextString(m) }
func (*P4DataTypeSpec) ProtoMessage()    {}
func (*P4DataTypeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{1}
}

func (m *P4DataTypeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4DataTypeSpec.Unmarshal(m, b)
}
func (m *P4DataTypeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4DataTypeSpec.Marshal(b, m, deterministic)
}
func (m *P4DataTypeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4DataTypeSpec.Merge(m, src)
}
func (m *P4DataTypeSpec) XXX_Size() int {
	return xxx_messageInfo_P4DataTypeSpec.Size(m)
}
func (m *P4DataTypeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_P4DataTypeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_P4DataTypeSpec proto.InternalMessageInfo

type isP4DataTypeSpec_TypeSpec interface {
	isP4DataTypeSpec_TypeSpec()
}

type P4DataTypeSpec_Bitstring struct {
	Bitstring *P4BitstringLikeTypeSpec `protobuf:"bytes,1,opt,name=bitstring,proto3,oneof"`
}

type P4DataTypeSpec_Bool struct {
	Bool *P4BoolType `protobuf:"bytes,2,opt,name=bool,proto3,oneof"`
}

type P4DataTypeSpec_Tuple struct {
	Tuple *P4TupleTypeSpec `protobuf:"bytes,3,opt,name=tuple,proto3,oneof"`
}

type P4DataTypeSpec_Struct struct {
	Struct *P4NamedType `protobuf:"bytes,4,opt,name=struct,proto3,oneof"`
}

type P4DataTypeSpec_Header struct {
	Header *P4NamedType `protobuf:"bytes,5,opt,name=header,proto3,oneof"`
}

type P4DataTypeSpec_HeaderUnion struct {
	HeaderUnion *P4NamedType `protobuf:"bytes,6,opt,name=header_union,json=headerUnion,proto3,oneof"`
}

type P4DataTypeSpec_HeaderStack struct {
	HeaderStack *P4HeaderStackTypeSpec `protobuf:"bytes,7,opt,name=header_stack,json=headerStack,proto3,oneof"`
}

type P4DataTypeSpec_HeaderUnionStack struct {
	HeaderUnionStack *P4HeaderUnionStackTypeSpec `protobuf:"bytes,8,opt,name=header_union_stack,json=headerUnionStack,proto3,oneof"`
}

type P4DataTypeSpec_Enum struct {
	Enum *P4NamedType `protobuf:"bytes,9,opt,name=enum,proto3,oneof"`
}

type P4DataTypeSpec_Error struct {
	Error *P4ErrorType `protobuf:"bytes,10,opt,name=error,proto3,oneof"`
}

type P4DataTypeSpec_SerializableEnum struct {
	SerializableEnum *P4NamedType `protobuf:"bytes,11,opt,name=serializable_enum,json=serializableEnum,proto3,oneof"`
}

type P4DataTypeSpec_NewType struct {
	NewType *P4NamedType `protobuf:"bytes,12,opt,name=new_type,json=newType,proto3,oneof"`
}

func (*P4DataTypeSpec_Bitstring) isP4DataTypeSpec_TypeSpec() {}

func (*P4DataTypeSpec_Bool) isP4DataTypeSpec_TypeSpec() {}

func (*P4DataTypeSpec_Tuple) isP4DataTypeSpec_TypeSpec() {}

func (*P4DataTypeSpec_Struct) isP4DataTypeSpec_TypeSpec() {}

func (*P4DataTypeSpec_Header) isP4DataTypeSpec_TypeSpec() {}

func (*P4DataTypeSpec_HeaderUnion) isP4DataTypeSpec_TypeSpec() {}

func (*P4DataTypeSpec_HeaderStack) isP4DataTypeSpec_TypeSpec() {}

func (*P4DataTypeSpec_HeaderUnionStack) isP4DataTypeSpec_TypeSpec() {}

func (*P4DataTypeSpec_Enum) isP4DataTypeSpec_TypeSpec() {}

func (*P4DataTypeSpec_Error) isP4DataTypeSpec_TypeSpec() {}

func (*P4DataTypeSpec_SerializableEnum) isP4DataTypeSpec_TypeSpec() {}

func (*P4DataTypeSpec_NewType) isP4DataTypeSpec_TypeSpec() {}

func (m *P4DataTypeSpec) GetTypeSpec() isP4DataTypeSpec_TypeSpec {
	if m != nil {
		return m.TypeSpec
	}
	return nil
}

func (m *P4DataTypeSpec) GetBitstring() *P4BitstringLikeTypeSpec {
	if x, ok := m.GetTypeSpec().(*P4DataTypeSpec_Bitstring); ok {
		return x.Bitstring
	}
	return nil
}

func (m *P4DataTypeSpec) GetBool() *P4BoolType {
	if x, ok := m.GetTypeSpec().(*P4DataTypeSpec_Bool); ok {
		return x.Bool
	}
	return nil
}

func (m *P4DataTypeSpec) GetTuple() *P4TupleTypeSpec {
	if x, ok := m.GetTypeSpec().(*P4DataTypeSpec_Tuple); ok {
		return x.Tuple
	}
	return nil
}

func (m *P4DataTypeSpec) GetStruct() *P4NamedType {
	if x, ok := m.GetTypeSpec().(*P4DataTypeSpec_Struct); ok {
		return x.Struct
	}
	return nil
}

func (m *P4DataTypeSpec) GetHeader() *P4NamedType {
	if x, ok := m.GetTypeSpec().(*P4DataTypeSpec_Header); ok {
		return x.Header
	}
	return nil
}

func (m *P4DataTypeSpec) GetHeaderUnion() *P4NamedType {
	if x, ok := m.GetTypeSpec().(*P4DataTypeSpec_HeaderUnion); ok {
		return x.HeaderUnion
	}
	return nil
}

func (m *P4DataTypeSpec) GetHeaderStack() *P4HeaderStackTypeSpec {
	if x, ok := m.GetTypeSpec().(*P4DataTypeSpec_HeaderStack); ok {
		return x.HeaderStack
	}
	return nil
}

func (m *P4DataTypeSpec) GetHeaderUnionStack() *P4HeaderUnionStackTypeSpec {
	if x, ok := m.GetTypeSpec().(*P4DataTypeSpec_HeaderUnionStack); ok {
		return x.HeaderUnionStack
	}
	return nil
}

func (m *P4DataTypeSpec) GetEnum() *P4NamedType {
	if x, ok := m.GetTypeSpec().(*P4DataTypeSpec_Enum); ok {
		return x.Enum
	}
	return nil
}

func (m *P4DataTypeSpec) GetError() *P4ErrorType {
	if x, ok := m.GetTypeSpec().(*P4DataTypeSpec_Error); ok {
		return x.Error
	}
	return nil
}

func (m *P4DataTypeSpec) GetSerializableEnum() *P4NamedType {
	if x, ok := m.GetTypeSpec().(*P4DataTypeSpec_SerializableEnum); ok {
		return x.SerializableEnum
	}
	return nil
}

func (m *P4DataTypeSpec) GetNewType() *P4NamedType {
	if x, ok := m.GetTypeSpec().(*P4DataTypeSpec_NewType); ok {
		return x.NewType
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*P4DataTypeSpec) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*P4DataTypeSpec_Bitstring)(nil),
		(*P4DataTypeSpec_Bool)(nil),
		(*P4DataTypeSpec_Tuple)(nil),
		(*P4DataTypeSpec_Struct)(nil),
		(*P4DataTypeSpec_Header)(nil),
		(*P4DataTypeSpec_HeaderUnion)(nil),
		(*P4DataTypeSpec_HeaderStack)(nil),
		(*P4DataTypeSpec_HeaderUnionStack)(nil),
		(*P4DataTypeSpec_Enum)(nil),
		(*P4DataTypeSpec_Error)(nil),
		(*P4DataTypeSpec_SerializableEnum)(nil),
		(*P4DataTypeSpec_NewType)(nil),
	}
}

type P4NamedType struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P4NamedType) Reset()         { *m = P4NamedType{} }
func (m *P4NamedType) String() string { return proto.CompactTextString(m) }
func (*P4NamedType) ProtoMessage()    {}
func (*P4NamedType) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{2}
}

func (m *P4NamedType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4NamedType.Unmarshal(m, b)
}
func (m *P4NamedType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4NamedType.Marshal(b, m, deterministic)
}
func (m *P4NamedType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4NamedType.Merge(m, src)
}
func (m *P4NamedType) XXX_Size() int {
	return xxx_messageInfo_P4NamedType.Size(m)
}
func (m *P4NamedType) XXX_DiscardUnknown() {
	xxx_messageInfo_P4NamedType.DiscardUnknown(m)
}

var xxx_messageInfo_P4NamedType proto.InternalMessageInfo

func (m *P4NamedType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Empty message as no type information needed, just used as a placeholder in
// the oneof to identify boolean types.
type P4BoolType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P4BoolType) Reset()         { *m = P4BoolType{} }
func (m *P4BoolType) String() string { return proto.CompactTextString(m) }
func (*P4BoolType) ProtoMessage()    {}
func (*P4BoolType) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{3}
}

func (m *P4BoolType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4BoolType.Unmarshal(m, b)
}
func (m *P4BoolType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4BoolType.Marshal(b, m, deterministic)
}
func (m *P4BoolType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4BoolType.Merge(m, src)
}
func (m *P4BoolType) XXX_Size() int {
	return xxx_messageInfo_P4BoolType.Size(m)
}
func (m *P4BoolType) XXX_DiscardUnknown() {
	xxx_messageInfo_P4BoolType.DiscardUnknown(m)
}

var xxx_messageInfo_P4BoolType proto.InternalMessageInfo

type P4ErrorType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P4ErrorType) Reset()         { *m = P4ErrorType{} }
func (m *P4ErrorType) String() string { return proto.CompactTextString(m) }
func (*P4ErrorType) ProtoMessage()    {}
func (*P4ErrorType) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{4}
}

func (m *P4ErrorType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4ErrorType.Unmarshal(m, b)
}
func (m *P4ErrorType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4ErrorType.Marshal(b, m, deterministic)
}
func (m *P4ErrorType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4ErrorType.Merge(m, src)
}
func (m *P4ErrorType) XXX_Size() int {
	return xxx_messageInfo_P4ErrorType.Size(m)
}
func (m *P4ErrorType) XXX_DiscardUnknown() {
	xxx_messageInfo_P4ErrorType.DiscardUnknown(m)
}

var xxx_messageInfo_P4ErrorType proto.InternalMessageInfo

type P4BitstringLikeTypeSpec struct {
	// Types that are valid to be assigned to TypeSpec:
	//	*P4BitstringLikeTypeSpec_Bit
	//	*P4BitstringLikeTypeSpec_Int
	//	*P4BitstringLikeTypeSpec_Varbit
	TypeSpec isP4BitstringLikeTypeSpec_TypeSpec `protobuf_oneof:"type_spec"`
	// Useful to identify well-known types, such as IP address or Ethernet MAC
	// address.
	Annotations          []string `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P4BitstringLikeTypeSpec) Reset()         { *m = P4BitstringLikeTypeSpec{} }
func (m *P4BitstringLikeTypeSpec) String() string { return proto.CompactTextString(m) }
func (*P4BitstringLikeTypeSpec) ProtoMessage()    {}
func (*P4BitstringLikeTypeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{5}
}

func (m *P4BitstringLikeTypeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4BitstringLikeTypeSpec.Unmarshal(m, b)
}
func (m *P4BitstringLikeTypeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4BitstringLikeTypeSpec.Marshal(b, m, deterministic)
}
func (m *P4BitstringLikeTypeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4BitstringLikeTypeSpec.Merge(m, src)
}
func (m *P4BitstringLikeTypeSpec) XXX_Size() int {
	return xxx_messageInfo_P4BitstringLikeTypeSpec.Size(m)
}
func (m *P4BitstringLikeTypeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_P4BitstringLikeTypeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_P4BitstringLikeTypeSpec proto.InternalMessageInfo

type isP4BitstringLikeTypeSpec_TypeSpec interface {
	isP4BitstringLikeTypeSpec_TypeSpec()
}

type P4BitstringLikeTypeSpec_Bit struct {
	Bit *P4BitTypeSpec `protobuf:"bytes,1,opt,name=bit,proto3,oneof"`
}

type P4BitstringLikeTypeSpec_Int struct {
	Int *P4IntTypeSpec `protobuf:"bytes,2,opt,name=int,proto3,oneof"`
}

type P4BitstringLikeTypeSpec_Varbit struct {
	Varbit *P4VarbitTypeSpec `protobuf:"bytes,3,opt,name=varbit,proto3,oneof"`
}

func (*P4BitstringLikeTypeSpec_Bit) isP4BitstringLikeTypeSpec_TypeSpec() {}

func (*P4BitstringLikeTypeSpec_Int) isP4BitstringLikeTypeSpec_TypeSpec() {}

func (*P4BitstringLikeTypeSpec_Varbit) isP4BitstringLikeTypeSpec_TypeSpec() {}

func (m *P4BitstringLikeTypeSpec) GetTypeSpec() isP4BitstringLikeTypeSpec_TypeSpec {
	if m != nil {
		return m.TypeSpec
	}
	return nil
}

func (m *P4BitstringLikeTypeSpec) GetBit() *P4BitTypeSpec {
	if x, ok := m.GetTypeSpec().(*P4BitstringLikeTypeSpec_Bit); ok {
		return x.Bit
	}
	return nil
}

func (m *P4BitstringLikeTypeSpec) GetInt() *P4IntTypeSpec {
	if x, ok := m.GetTypeSpec().(*P4BitstringLikeTypeSpec_Int); ok {
		return x.Int
	}
	return nil
}

func (m *P4BitstringLikeTypeSpec) GetVarbit() *P4VarbitTypeSpec {
	if x, ok := m.GetTypeSpec().(*P4BitstringLikeTypeSpec_Varbit); ok {
		return x.Varbit
	}
	return nil
}

func (m *P4BitstringLikeTypeSpec) GetAnnotations() []string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*P4BitstringLikeTypeSpec) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*P4BitstringLikeTypeSpec_Bit)(nil),
		(*P4BitstringLikeTypeSpec_Int)(nil),
		(*P4BitstringLikeTypeSpec_Varbit)(nil),
	}
}

type P4BitTypeSpec struct {
	Bitwidth             int32    `protobuf:"varint,1,opt,name=bitwidth,proto3" json:"bitwidth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P4BitTypeSpec) Reset()         { *m = P4BitTypeSpec{} }
func (m *P4BitTypeSpec) String() string { return proto.CompactTextString(m) }
func (*P4BitTypeSpec) ProtoMessage()    {}
func (*P4BitTypeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{6}
}

func (m *P4BitTypeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4BitTypeSpec.Unmarshal(m, b)
}
func (m *P4BitTypeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4BitTypeSpec.Marshal(b, m, deterministic)
}
func (m *P4BitTypeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4BitTypeSpec.Merge(m, src)
}
func (m *P4BitTypeSpec) XXX_Size() int {
	return xxx_messageInfo_P4BitTypeSpec.Size(m)
}
func (m *P4BitTypeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_P4BitTypeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_P4BitTypeSpec proto.InternalMessageInfo

func (m *P4BitTypeSpec) GetBitwidth() int32 {
	if m != nil {
		return m.Bitwidth
	}
	return 0
}

type P4IntTypeSpec struct {
	Bitwidth             int32    `protobuf:"varint,1,opt,name=bitwidth,proto3" json:"bitwidth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P4IntTypeSpec) Reset()         { *m = P4IntTypeSpec{} }
func (m *P4IntTypeSpec) String() string { return proto.CompactTextString(m) }
func (*P4IntTypeSpec) ProtoMessage()    {}
func (*P4IntTypeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{7}
}

func (m *P4IntTypeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4IntTypeSpec.Unmarshal(m, b)
}
func (m *P4IntTypeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4IntTypeSpec.Marshal(b, m, deterministic)
}
func (m *P4IntTypeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4IntTypeSpec.Merge(m, src)
}
func (m *P4IntTypeSpec) XXX_Size() int {
	return xxx_messageInfo_P4IntTypeSpec.Size(m)
}
func (m *P4IntTypeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_P4IntTypeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_P4IntTypeSpec proto.InternalMessageInfo

func (m *P4IntTypeSpec) GetBitwidth() int32 {
	if m != nil {
		return m.Bitwidth
	}
	return 0
}

type P4VarbitTypeSpec struct {
	MaxBitwidth          int32    `protobuf:"varint,1,opt,name=max_bitwidth,json=maxBitwidth,proto3" json:"max_bitwidth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P4VarbitTypeSpec) Reset()         { *m = P4VarbitTypeSpec{} }
func (m *P4VarbitTypeSpec) String() string { return proto.CompactTextString(m) }
func (*P4VarbitTypeSpec) ProtoMessage()    {}
func (*P4VarbitTypeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{8}
}

func (m *P4VarbitTypeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4VarbitTypeSpec.Unmarshal(m, b)
}
func (m *P4VarbitTypeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4VarbitTypeSpec.Marshal(b, m, deterministic)
}
func (m *P4VarbitTypeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4VarbitTypeSpec.Merge(m, src)
}
func (m *P4VarbitTypeSpec) XXX_Size() int {
	return xxx_messageInfo_P4VarbitTypeSpec.Size(m)
}
func (m *P4VarbitTypeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_P4VarbitTypeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_P4VarbitTypeSpec proto.InternalMessageInfo

func (m *P4VarbitTypeSpec) GetMaxBitwidth() int32 {
	if m != nil {
		return m.MaxBitwidth
	}
	return 0
}

// From the P4_16 spec: "A tuple is similar to a struct, in that it holds
// multiple values. Unlike a struct type, tuples have no named fields."
type P4TupleTypeSpec struct {
	Members              []*P4DataTypeSpec `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *P4TupleTypeSpec) Reset()         { *m = P4TupleTypeSpec{} }
func (m *P4TupleTypeSpec) String() string { return proto.CompactTextString(m) }
func (*P4TupleTypeSpec) ProtoMessage()    {}
func (*P4TupleTypeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{9}
}

func (m *P4TupleTypeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4TupleTypeSpec.Unmarshal(m, b)
}
func (m *P4TupleTypeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4TupleTypeSpec.Marshal(b, m, deterministic)
}
func (m *P4TupleTypeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4TupleTypeSpec.Merge(m, src)
}
func (m *P4TupleTypeSpec) XXX_Size() int {
	return xxx_messageInfo_P4TupleTypeSpec.Size(m)
}
func (m *P4TupleTypeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_P4TupleTypeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_P4TupleTypeSpec proto.InternalMessageInfo

func (m *P4TupleTypeSpec) GetMembers() []*P4DataTypeSpec {
	if m != nil {
		return m.Members
	}
	return nil
}

type P4StructTypeSpec struct {
	Members              []*P4StructTypeSpec_Member `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Annotations          []string                   `protobuf:"bytes,2,rep,name=annotations,proto3" json:"annotations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *P4StructTypeSpec) Reset()         { *m = P4StructTypeSpec{} }
func (m *P4StructTypeSpec) String() string { return proto.CompactTextString(m) }
func (*P4StructTypeSpec) ProtoMessage()    {}
func (*P4StructTypeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{10}
}

func (m *P4StructTypeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4StructTypeSpec.Unmarshal(m, b)
}
func (m *P4StructTypeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4StructTypeSpec.Marshal(b, m, deterministic)
}
func (m *P4StructTypeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4StructTypeSpec.Merge(m, src)
}
func (m *P4StructTypeSpec) XXX_Size() int {
	return xxx_messageInfo_P4StructTypeSpec.Size(m)
}
func (m *P4StructTypeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_P4StructTypeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_P4StructTypeSpec proto.InternalMessageInfo

func (m *P4StructTypeSpec) GetMembers() []*P4StructTypeSpec_Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *P4StructTypeSpec) GetAnnotations() []string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

type P4StructTypeSpec_Member struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TypeSpec             *P4DataTypeSpec `protobuf:"bytes,2,opt,name=type_spec,json=typeSpec,proto3" json:"type_spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *P4StructTypeSpec_Member) Reset()         { *m = P4StructTypeSpec_Member{} }
func (m *P4StructTypeSpec_Member) String() string { return proto.CompactTextString(m) }
func (*P4StructTypeSpec_Member) ProtoMessage()    {}
func (*P4StructTypeSpec_Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{10, 0}
}

func (m *P4StructTypeSpec_Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4StructTypeSpec_Member.Unmarshal(m, b)
}
func (m *P4StructTypeSpec_Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4StructTypeSpec_Member.Marshal(b, m, deterministic)
}
func (m *P4StructTypeSpec_Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4StructTypeSpec_Member.Merge(m, src)
}
func (m *P4StructTypeSpec_Member) XXX_Size() int {
	return xxx_messageInfo_P4StructTypeSpec_Member.Size(m)
}
func (m *P4StructTypeSpec_Member) XXX_DiscardUnknown() {
	xxx_messageInfo_P4StructTypeSpec_Member.DiscardUnknown(m)
}

var xxx_messageInfo_P4StructTypeSpec_Member proto.InternalMessageInfo

func (m *P4StructTypeSpec_Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *P4StructTypeSpec_Member) GetTypeSpec() *P4DataTypeSpec {
	if m != nil {
		return m.TypeSpec
	}
	return nil
}

type P4HeaderTypeSpec struct {
	Members              []*P4HeaderTypeSpec_Member `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Annotations          []string                   `protobuf:"bytes,2,rep,name=annotations,proto3" json:"annotations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *P4HeaderTypeSpec) Reset()         { *m = P4HeaderTypeSpec{} }
func (m *P4HeaderTypeSpec) String() string { return proto.CompactTextString(m) }
func (*P4HeaderTypeSpec) ProtoMessage()    {}
func (*P4HeaderTypeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{11}
}

func (m *P4HeaderTypeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4HeaderTypeSpec.Unmarshal(m, b)
}
func (m *P4HeaderTypeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4HeaderTypeSpec.Marshal(b, m, deterministic)
}
func (m *P4HeaderTypeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4HeaderTypeSpec.Merge(m, src)
}
func (m *P4HeaderTypeSpec) XXX_Size() int {
	return xxx_messageInfo_P4HeaderTypeSpec.Size(m)
}
func (m *P4HeaderTypeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_P4HeaderTypeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_P4HeaderTypeSpec proto.InternalMessageInfo

func (m *P4HeaderTypeSpec) GetMembers() []*P4HeaderTypeSpec_Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *P4HeaderTypeSpec) GetAnnotations() []string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

type P4HeaderTypeSpec_Member struct {
	Name                 string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TypeSpec             *P4BitstringLikeTypeSpec `protobuf:"bytes,2,opt,name=type_spec,json=typeSpec,proto3" json:"type_spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *P4HeaderTypeSpec_Member) Reset()         { *m = P4HeaderTypeSpec_Member{} }
func (m *P4HeaderTypeSpec_Member) String() string { return proto.CompactTextString(m) }
func (*P4HeaderTypeSpec_Member) ProtoMessage()    {}
func (*P4HeaderTypeSpec_Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{11, 0}
}

func (m *P4HeaderTypeSpec_Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4HeaderTypeSpec_Member.Unmarshal(m, b)
}
func (m *P4HeaderTypeSpec_Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4HeaderTypeSpec_Member.Marshal(b, m, deterministic)
}
func (m *P4HeaderTypeSpec_Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4HeaderTypeSpec_Member.Merge(m, src)
}
func (m *P4HeaderTypeSpec_Member) XXX_Size() int {
	return xxx_messageInfo_P4HeaderTypeSpec_Member.Size(m)
}
func (m *P4HeaderTypeSpec_Member) XXX_DiscardUnknown() {
	xxx_messageInfo_P4HeaderTypeSpec_Member.DiscardUnknown(m)
}

var xxx_messageInfo_P4HeaderTypeSpec_Member proto.InternalMessageInfo

func (m *P4HeaderTypeSpec_Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *P4HeaderTypeSpec_Member) GetTypeSpec() *P4BitstringLikeTypeSpec {
	if m != nil {
		return m.TypeSpec
	}
	return nil
}

type P4HeaderUnionTypeSpec struct {
	Members              []*P4HeaderUnionTypeSpec_Member `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Annotations          []string                        `protobuf:"bytes,2,rep,name=annotations,proto3" json:"annotations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *P4HeaderUnionTypeSpec) Reset()         { *m = P4HeaderUnionTypeSpec{} }
func (m *P4HeaderUnionTypeSpec) String() string { return proto.CompactTextString(m) }
func (*P4HeaderUnionTypeSpec) ProtoMessage()    {}
func (*P4HeaderUnionTypeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{12}
}

func (m *P4HeaderUnionTypeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4HeaderUnionTypeSpec.Unmarshal(m, b)
}
func (m *P4HeaderUnionTypeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4HeaderUnionTypeSpec.Marshal(b, m, deterministic)
}
func (m *P4HeaderUnionTypeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4HeaderUnionTypeSpec.Merge(m, src)
}
func (m *P4HeaderUnionTypeSpec) XXX_Size() int {
	return xxx_messageInfo_P4HeaderUnionTypeSpec.Size(m)
}
func (m *P4HeaderUnionTypeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_P4HeaderUnionTypeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_P4HeaderUnionTypeSpec proto.InternalMessageInfo

func (m *P4HeaderUnionTypeSpec) GetMembers() []*P4HeaderUnionTypeSpec_Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *P4HeaderUnionTypeSpec) GetAnnotations() []string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

type P4HeaderUnionTypeSpec_Member struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Header               *P4NamedType `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *P4HeaderUnionTypeSpec_Member) Reset()         { *m = P4HeaderUnionTypeSpec_Member{} }
func (m *P4HeaderUnionTypeSpec_Member) String() string { return proto.CompactTextString(m) }
func (*P4HeaderUnionTypeSpec_Member) ProtoMessage()    {}
func (*P4HeaderUnionTypeSpec_Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{12, 0}
}

func (m *P4HeaderUnionTypeSpec_Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4HeaderUnionTypeSpec_Member.Unmarshal(m, b)
}
func (m *P4HeaderUnionTypeSpec_Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4HeaderUnionTypeSpec_Member.Marshal(b, m, deterministic)
}
func (m *P4HeaderUnionTypeSpec_Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4HeaderUnionTypeSpec_Member.Merge(m, src)
}
func (m *P4HeaderUnionTypeSpec_Member) XXX_Size() int {
	return xxx_messageInfo_P4HeaderUnionTypeSpec_Member.Size(m)
}
func (m *P4HeaderUnionTypeSpec_Member) XXX_DiscardUnknown() {
	xxx_messageInfo_P4HeaderUnionTypeSpec_Member.DiscardUnknown(m)
}

var xxx_messageInfo_P4HeaderUnionTypeSpec_Member proto.InternalMessageInfo

func (m *P4HeaderUnionTypeSpec_Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *P4HeaderUnionTypeSpec_Member) GetHeader() *P4NamedType {
	if m != nil {
		return m.Header
	}
	return nil
}

type P4HeaderStackTypeSpec struct {
	Header               *P4NamedType `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Size                 int32        `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *P4HeaderStackTypeSpec) Reset()         { *m = P4HeaderStackTypeSpec{} }
func (m *P4HeaderStackTypeSpec) String() string { return proto.CompactTextString(m) }
func (*P4HeaderStackTypeSpec) ProtoMessage()    {}
func (*P4HeaderStackTypeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{13}
}

func (m *P4HeaderStackTypeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4HeaderStackTypeSpec.Unmarshal(m, b)
}
func (m *P4HeaderStackTypeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4HeaderStackTypeSpec.Marshal(b, m, deterministic)
}
func (m *P4HeaderStackTypeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4HeaderStackTypeSpec.Merge(m, src)
}
func (m *P4HeaderStackTypeSpec) XXX_Size() int {
	return xxx_messageInfo_P4HeaderStackTypeSpec.Size(m)
}
func (m *P4HeaderStackTypeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_P4HeaderStackTypeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_P4HeaderStackTypeSpec proto.InternalMessageInfo

func (m *P4HeaderStackTypeSpec) GetHeader() *P4NamedType {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *P4HeaderStackTypeSpec) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type P4HeaderUnionStackTypeSpec struct {
	HeaderUnion          *P4NamedType `protobuf:"bytes,1,opt,name=header_union,json=headerUnion,proto3" json:"header_union,omitempty"`
	Size                 int32        `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *P4HeaderUnionStackTypeSpec) Reset()         { *m = P4HeaderUnionStackTypeSpec{} }
func (m *P4HeaderUnionStackTypeSpec) String() string { return proto.CompactTextString(m) }
func (*P4HeaderUnionStackTypeSpec) ProtoMessage()    {}
func (*P4HeaderUnionStackTypeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{14}
}

func (m *P4HeaderUnionStackTypeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4HeaderUnionStackTypeSpec.Unmarshal(m, b)
}
func (m *P4HeaderUnionStackTypeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4HeaderUnionStackTypeSpec.Marshal(b, m, deterministic)
}
func (m *P4HeaderUnionStackTypeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4HeaderUnionStackTypeSpec.Merge(m, src)
}
func (m *P4HeaderUnionStackTypeSpec) XXX_Size() int {
	return xxx_messageInfo_P4HeaderUnionStackTypeSpec.Size(m)
}
func (m *P4HeaderUnionStackTypeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_P4HeaderUnionStackTypeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_P4HeaderUnionStackTypeSpec proto.InternalMessageInfo

func (m *P4HeaderUnionStackTypeSpec) GetHeaderUnion() *P4NamedType {
	if m != nil {
		return m.HeaderUnion
	}
	return nil
}

func (m *P4HeaderUnionStackTypeSpec) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type KeyValuePair struct {
	Key                  string      `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *Expression `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *KeyValuePair) Reset()         { *m = KeyValuePair{} }
func (m *KeyValuePair) String() string { return proto.CompactTextString(m) }
func (*KeyValuePair) ProtoMessage()    {}
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{15}
}

func (m *KeyValuePair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValuePair.Unmarshal(m, b)
}
func (m *KeyValuePair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValuePair.Marshal(b, m, deterministic)
}
func (m *KeyValuePair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValuePair.Merge(m, src)
}
func (m *KeyValuePair) XXX_Size() int {
	return xxx_messageInfo_KeyValuePair.Size(m)
}
func (m *KeyValuePair) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValuePair.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValuePair proto.InternalMessageInfo

func (m *KeyValuePair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValuePair) GetValue() *Expression {
	if m != nil {
		return m.Value
	}
	return nil
}

type KeyValuePairList struct {
	KvPairs              []*KeyValuePair `protobuf:"bytes,1,rep,name=kv_pairs,json=kvPairs,proto3" json:"kv_pairs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *KeyValuePairList) Reset()         { *m = KeyValuePairList{} }
func (m *KeyValuePairList) String() string { return proto.CompactTextString(m) }
func (*KeyValuePairList) ProtoMessage()    {}
func (*KeyValuePairList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{16}
}

func (m *KeyValuePairList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValuePairList.Unmarshal(m, b)
}
func (m *KeyValuePairList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValuePairList.Marshal(b, m, deterministic)
}
func (m *KeyValuePairList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValuePairList.Merge(m, src)
}
func (m *KeyValuePairList) XXX_Size() int {
	return xxx_messageInfo_KeyValuePairList.Size(m)
}
func (m *KeyValuePairList) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValuePairList.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValuePairList proto.InternalMessageInfo

func (m *KeyValuePairList) GetKvPairs() []*KeyValuePair {
	if m != nil {
		return m.KvPairs
	}
	return nil
}

type Expression struct {
	// Types that are valid to be assigned to Value:
	//	*Expression_StringValue
	//	*Expression_Int64Value
	//	*Expression_BoolValue
	Value                isExpression_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Expression) Reset()         { *m = Expression{} }
func (m *Expression) String() string { return proto.CompactTextString(m) }
func (*Expression) ProtoMessage()    {}
func (*Expression) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{17}
}

func (m *Expression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expression.Unmarshal(m, b)
}
func (m *Expression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expression.Marshal(b, m, deterministic)
}
func (m *Expression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expression.Merge(m, src)
}
func (m *Expression) XXX_Size() int {
	return xxx_messageInfo_Expression.Size(m)
}
func (m *Expression) XXX_DiscardUnknown() {
	xxx_messageInfo_Expression.DiscardUnknown(m)
}

var xxx_messageInfo_Expression proto.InternalMessageInfo

type isExpression_Value interface {
	isExpression_Value()
}

type Expression_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Expression_Int64Value struct {
	Int64Value int64 `protobuf:"varint,2,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Expression_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*Expression_StringValue) isExpression_Value() {}

func (*Expression_Int64Value) isExpression_Value() {}

func (*Expression_BoolValue) isExpression_Value() {}

func (m *Expression) GetValue() isExpression_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Expression) GetStringValue() string {
	if x, ok := m.GetValue().(*Expression_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Expression) GetInt64Value() int64 {
	if x, ok := m.GetValue().(*Expression_Int64Value); ok {
		return x.Int64Value
	}
	return 0
}

func (m *Expression) GetBoolValue() bool {
	if x, ok := m.GetValue().(*Expression_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Expression) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Expression_StringValue)(nil),
		(*Expression_Int64Value)(nil),
		(*Expression_BoolValue)(nil),
	}
}

type ExpressionList struct {
	Expressions          []*Expression `protobuf:"bytes,1,rep,name=expressions,proto3" json:"expressions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ExpressionList) Reset()         { *m = ExpressionList{} }
func (m *ExpressionList) String() string { return proto.CompactTextString(m) }
func (*ExpressionList) ProtoMessage()    {}
func (*ExpressionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{18}
}

func (m *ExpressionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpressionList.Unmarshal(m, b)
}
func (m *ExpressionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpressionList.Marshal(b, m, deterministic)
}
func (m *ExpressionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpressionList.Merge(m, src)
}
func (m *ExpressionList) XXX_Size() int {
	return xxx_messageInfo_ExpressionList.Size(m)
}
func (m *ExpressionList) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpressionList.DiscardUnknown(m)
}

var xxx_messageInfo_ExpressionList proto.InternalMessageInfo

func (m *ExpressionList) GetExpressions() []*Expression {
	if m != nil {
		return m.Expressions
	}
	return nil
}

type StructuredAnnotation struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Body:
	//	*StructuredAnnotation_ExpressionList
	//	*StructuredAnnotation_KvPairList
	Body                 isStructuredAnnotation_Body `protobuf_oneof:"body"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *StructuredAnnotation) Reset()         { *m = StructuredAnnotation{} }
func (m *StructuredAnnotation) String() string { return proto.CompactTextString(m) }
func (*StructuredAnnotation) ProtoMessage()    {}
func (*StructuredAnnotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{19}
}

func (m *StructuredAnnotation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructuredAnnotation.Unmarshal(m, b)
}
func (m *StructuredAnnotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructuredAnnotation.Marshal(b, m, deterministic)
}
func (m *StructuredAnnotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructuredAnnotation.Merge(m, src)
}
func (m *StructuredAnnotation) XXX_Size() int {
	return xxx_messageInfo_StructuredAnnotation.Size(m)
}
func (m *StructuredAnnotation) XXX_DiscardUnknown() {
	xxx_messageInfo_StructuredAnnotation.DiscardUnknown(m)
}

var xxx_messageInfo_StructuredAnnotation proto.InternalMessageInfo

func (m *StructuredAnnotation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isStructuredAnnotation_Body interface {
	isStructuredAnnotation_Body()
}

type StructuredAnnotation_ExpressionList struct {
	ExpressionList *ExpressionList `protobuf:"bytes,2,opt,name=expression_list,json=expressionList,proto3,oneof"`
}

type StructuredAnnotation_KvPairList struct {
	KvPairList *KeyValuePairList `protobuf:"bytes,3,opt,name=kv_pair_list,json=kvPairList,proto3,oneof"`
}

func (*StructuredAnnotation_ExpressionList) isStructuredAnnotation_Body() {}

func (*StructuredAnnotation_KvPairList) isStructuredAnnotation_Body() {}

func (m *StructuredAnnotation) GetBody() isStructuredAnnotation_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *StructuredAnnotation) GetExpressionList() *ExpressionList {
	if x, ok := m.GetBody().(*StructuredAnnotation_ExpressionList); ok {
		return x.ExpressionList
	}
	return nil
}

func (m *StructuredAnnotation) GetKvPairList() *KeyValuePairList {
	if x, ok := m.GetBody().(*StructuredAnnotation_KvPairList); ok {
		return x.KvPairList
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StructuredAnnotation) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StructuredAnnotation_ExpressionList)(nil),
		(*StructuredAnnotation_KvPairList)(nil),
	}
}

// For "safe" enums with no underlying representation and no member integer
// values.
type P4EnumTypeSpec struct {
	Members               []*P4EnumTypeSpec_Member `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Annotations           []string                 `protobuf:"bytes,2,rep,name=annotations,proto3" json:"annotations,omitempty"`
	StructuredAnnotations []*StructuredAnnotation  `protobuf:"bytes,3,rep,name=structured_annotations,json=structuredAnnotations,proto3" json:"structured_annotations,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                 `json:"-"`
	XXX_unrecognized      []byte                   `json:"-"`
	XXX_sizecache         int32                    `json:"-"`
}

func (m *P4EnumTypeSpec) Reset()         { *m = P4EnumTypeSpec{} }
func (m *P4EnumTypeSpec) String() string { return proto.CompactTextString(m) }
func (*P4EnumTypeSpec) ProtoMessage()    {}
func (*P4EnumTypeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{20}
}

func (m *P4EnumTypeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4EnumTypeSpec.Unmarshal(m, b)
}
func (m *P4EnumTypeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4EnumTypeSpec.Marshal(b, m, deterministic)
}
func (m *P4EnumTypeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4EnumTypeSpec.Merge(m, src)
}
func (m *P4EnumTypeSpec) XXX_Size() int {
	return xxx_messageInfo_P4EnumTypeSpec.Size(m)
}
func (m *P4EnumTypeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_P4EnumTypeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_P4EnumTypeSpec proto.InternalMessageInfo

func (m *P4EnumTypeSpec) GetMembers() []*P4EnumTypeSpec_Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *P4EnumTypeSpec) GetAnnotations() []string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *P4EnumTypeSpec) GetStructuredAnnotations() []*StructuredAnnotation {
	if m != nil {
		return m.StructuredAnnotations
	}
	return nil
}

type P4EnumTypeSpec_Member struct {
	Name                  string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Annotations           []string                `protobuf:"bytes,2,rep,name=annotations,proto3" json:"annotations,omitempty"`
	StructuredAnnotations []*StructuredAnnotation `protobuf:"bytes,3,rep,name=structured_annotations,json=structuredAnnotations,proto3" json:"structured_annotations,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                `json:"-"`
	XXX_unrecognized      []byte                  `json:"-"`
	XXX_sizecache         int32                   `json:"-"`
}

func (m *P4EnumTypeSpec_Member) Reset()         { *m = P4EnumTypeSpec_Member{} }
func (m *P4EnumTypeSpec_Member) String() string { return proto.CompactTextString(m) }
func (*P4EnumTypeSpec_Member) ProtoMessage()    {}
func (*P4EnumTypeSpec_Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{20, 0}
}

func (m *P4EnumTypeSpec_Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4EnumTypeSpec_Member.Unmarshal(m, b)
}
func (m *P4EnumTypeSpec_Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4EnumTypeSpec_Member.Marshal(b, m, deterministic)
}
func (m *P4EnumTypeSpec_Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4EnumTypeSpec_Member.Merge(m, src)
}
func (m *P4EnumTypeSpec_Member) XXX_Size() int {
	return xxx_messageInfo_P4EnumTypeSpec_Member.Size(m)
}
func (m *P4EnumTypeSpec_Member) XXX_DiscardUnknown() {
	xxx_messageInfo_P4EnumTypeSpec_Member.DiscardUnknown(m)
}

var xxx_messageInfo_P4EnumTypeSpec_Member proto.InternalMessageInfo

func (m *P4EnumTypeSpec_Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *P4EnumTypeSpec_Member) GetAnnotations() []string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *P4EnumTypeSpec_Member) GetStructuredAnnotations() []*StructuredAnnotation {
	if m != nil {
		return m.StructuredAnnotations
	}
	return nil
}

// For serializable (or "unsafe") enums, which have an underlying type. Note
// that as per the P4_16 specification, the underlying representation can only
// be a bit<W> type.
type P4SerializableEnumTypeSpec struct {
	UnderlyingType        *P4BitTypeSpec                       `protobuf:"bytes,1,opt,name=underlying_type,json=underlyingType,proto3" json:"underlying_type,omitempty"`
	Members               []*P4SerializableEnumTypeSpec_Member `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	Annotations           []string                             `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty"`
	StructuredAnnotations []*StructuredAnnotation              `protobuf:"bytes,4,rep,name=structured_annotations,json=structuredAnnotations,proto3" json:"structured_annotations,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                             `json:"-"`
	XXX_unrecognized      []byte                               `json:"-"`
	XXX_sizecache         int32                                `json:"-"`
}

func (m *P4SerializableEnumTypeSpec) Reset()         { *m = P4SerializableEnumTypeSpec{} }
func (m *P4SerializableEnumTypeSpec) String() string { return proto.CompactTextString(m) }
func (*P4SerializableEnumTypeSpec) ProtoMessage()    {}
func (*P4SerializableEnumTypeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{21}
}

func (m *P4SerializableEnumTypeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4SerializableEnumTypeSpec.Unmarshal(m, b)
}
func (m *P4SerializableEnumTypeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4SerializableEnumTypeSpec.Marshal(b, m, deterministic)
}
func (m *P4SerializableEnumTypeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4SerializableEnumTypeSpec.Merge(m, src)
}
func (m *P4SerializableEnumTypeSpec) XXX_Size() int {
	return xxx_messageInfo_P4SerializableEnumTypeSpec.Size(m)
}
func (m *P4SerializableEnumTypeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_P4SerializableEnumTypeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_P4SerializableEnumTypeSpec proto.InternalMessageInfo

func (m *P4SerializableEnumTypeSpec) GetUnderlyingType() *P4BitTypeSpec {
	if m != nil {
		return m.UnderlyingType
	}
	return nil
}

func (m *P4SerializableEnumTypeSpec) GetMembers() []*P4SerializableEnumTypeSpec_Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *P4SerializableEnumTypeSpec) GetAnnotations() []string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *P4SerializableEnumTypeSpec) GetStructuredAnnotations() []*StructuredAnnotation {
	if m != nil {
		return m.StructuredAnnotations
	}
	return nil
}

type P4SerializableEnumTypeSpec_Member struct {
	Name                  string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                 []byte                  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Annotations           []string                `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty"`
	StructuredAnnotations []*StructuredAnnotation `protobuf:"bytes,4,rep,name=structured_annotations,json=structuredAnnotations,proto3" json:"structured_annotations,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                `json:"-"`
	XXX_unrecognized      []byte                  `json:"-"`
	XXX_sizecache         int32                   `json:"-"`
}

func (m *P4SerializableEnumTypeSpec_Member) Reset()         { *m = P4SerializableEnumTypeSpec_Member{} }
func (m *P4SerializableEnumTypeSpec_Member) String() string { return proto.CompactTextString(m) }
func (*P4SerializableEnumTypeSpec_Member) ProtoMessage()    {}
func (*P4SerializableEnumTypeSpec_Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{21, 0}
}

func (m *P4SerializableEnumTypeSpec_Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4SerializableEnumTypeSpec_Member.Unmarshal(m, b)
}
func (m *P4SerializableEnumTypeSpec_Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4SerializableEnumTypeSpec_Member.Marshal(b, m, deterministic)
}
func (m *P4SerializableEnumTypeSpec_Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4SerializableEnumTypeSpec_Member.Merge(m, src)
}
func (m *P4SerializableEnumTypeSpec_Member) XXX_Size() int {
	return xxx_messageInfo_P4SerializableEnumTypeSpec_Member.Size(m)
}
func (m *P4SerializableEnumTypeSpec_Member) XXX_DiscardUnknown() {
	xxx_messageInfo_P4SerializableEnumTypeSpec_Member.DiscardUnknown(m)
}

var xxx_messageInfo_P4SerializableEnumTypeSpec_Member proto.InternalMessageInfo

func (m *P4SerializableEnumTypeSpec_Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *P4SerializableEnumTypeSpec_Member) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *P4SerializableEnumTypeSpec_Member) GetAnnotations() []string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *P4SerializableEnumTypeSpec_Member) GetStructuredAnnotations() []*StructuredAnnotation {
	if m != nil {
		return m.StructuredAnnotations
	}
	return nil
}

// Similar to an enum, but there is always one and only one instance per P4
// program.
type P4ErrorTypeSpec struct {
	Members              []string `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P4ErrorTypeSpec) Reset()         { *m = P4ErrorTypeSpec{} }
func (m *P4ErrorTypeSpec) String() string { return proto.CompactTextString(m) }
func (*P4ErrorTypeSpec) ProtoMessage()    {}
func (*P4ErrorTypeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{22}
}

func (m *P4ErrorTypeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4ErrorTypeSpec.Unmarshal(m, b)
}
func (m *P4ErrorTypeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4ErrorTypeSpec.Marshal(b, m, deterministic)
}
func (m *P4ErrorTypeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4ErrorTypeSpec.Merge(m, src)
}
func (m *P4ErrorTypeSpec) XXX_Size() int {
	return xxx_messageInfo_P4ErrorTypeSpec.Size(m)
}
func (m *P4ErrorTypeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_P4ErrorTypeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_P4ErrorTypeSpec proto.InternalMessageInfo

func (m *P4ErrorTypeSpec) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

type P4NewTypeTranslation struct {
	// the URI uniquely identifies the translation in order to enable the
	// P4Runtime agent to perform value-mapping appropriately when required. It is
	// recommended that the URI includes at least the P4 architecture name and the
	// type name.
	Uri string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	// The object is either represented as an unsigned integer with a bitwidth of
	// `sdn_bitwidth`, or as a string.
	//
	// Types that are valid to be assigned to SdnType:
	//	*P4NewTypeTranslation_SdnBitwidth
	//	*P4NewTypeTranslation_SdnString_
	SdnType              isP4NewTypeTranslation_SdnType `protobuf_oneof:"sdn_type"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *P4NewTypeTranslation) Reset()         { *m = P4NewTypeTranslation{} }
func (m *P4NewTypeTranslation) String() string { return proto.CompactTextString(m) }
func (*P4NewTypeTranslation) ProtoMessage()    {}
func (*P4NewTypeTranslation) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{23}
}

func (m *P4NewTypeTranslation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4NewTypeTranslation.Unmarshal(m, b)
}
func (m *P4NewTypeTranslation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4NewTypeTranslation.Marshal(b, m, deterministic)
}
func (m *P4NewTypeTranslation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4NewTypeTranslation.Merge(m, src)
}
func (m *P4NewTypeTranslation) XXX_Size() int {
	return xxx_messageInfo_P4NewTypeTranslation.Size(m)
}
func (m *P4NewTypeTranslation) XXX_DiscardUnknown() {
	xxx_messageInfo_P4NewTypeTranslation.DiscardUnknown(m)
}

var xxx_messageInfo_P4NewTypeTranslation proto.InternalMessageInfo

func (m *P4NewTypeTranslation) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

type isP4NewTypeTranslation_SdnType interface {
	isP4NewTypeTranslation_SdnType()
}

type P4NewTypeTranslation_SdnBitwidth struct {
	SdnBitwidth int32 `protobuf:"varint,2,opt,name=sdn_bitwidth,json=sdnBitwidth,proto3,oneof"`
}

type P4NewTypeTranslation_SdnString_ struct {
	SdnString *P4NewTypeTranslation_SdnString `protobuf:"bytes,3,opt,name=sdn_string,json=sdnString,proto3,oneof"`
}

func (*P4NewTypeTranslation_SdnBitwidth) isP4NewTypeTranslation_SdnType() {}

func (*P4NewTypeTranslation_SdnString_) isP4NewTypeTranslation_SdnType() {}

func (m *P4NewTypeTranslation) GetSdnType() isP4NewTypeTranslation_SdnType {
	if m != nil {
		return m.SdnType
	}
	return nil
}

func (m *P4NewTypeTranslation) GetSdnBitwidth() int32 {
	if x, ok := m.GetSdnType().(*P4NewTypeTranslation_SdnBitwidth); ok {
		return x.SdnBitwidth
	}
	return 0
}

func (m *P4NewTypeTranslation) GetSdnString() *P4NewTypeTranslation_SdnString {
	if x, ok := m.GetSdnType().(*P4NewTypeTranslation_SdnString_); ok {
		return x.SdnString
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*P4NewTypeTranslation) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*P4NewTypeTranslation_SdnBitwidth)(nil),
		(*P4NewTypeTranslation_SdnString_)(nil),
	}
}

type P4NewTypeTranslation_SdnString struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P4NewTypeTranslation_SdnString) Reset()         { *m = P4NewTypeTranslation_SdnString{} }
func (m *P4NewTypeTranslation_SdnString) String() string { return proto.CompactTextString(m) }
func (*P4NewTypeTranslation_SdnString) ProtoMessage()    {}
func (*P4NewTypeTranslation_SdnString) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{23, 0}
}

func (m *P4NewTypeTranslation_SdnString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4NewTypeTranslation_SdnString.Unmarshal(m, b)
}
func (m *P4NewTypeTranslation_SdnString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4NewTypeTranslation_SdnString.Marshal(b, m, deterministic)
}
func (m *P4NewTypeTranslation_SdnString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4NewTypeTranslation_SdnString.Merge(m, src)
}
func (m *P4NewTypeTranslation_SdnString) XXX_Size() int {
	return xxx_messageInfo_P4NewTypeTranslation_SdnString.Size(m)
}
func (m *P4NewTypeTranslation_SdnString) XXX_DiscardUnknown() {
	xxx_messageInfo_P4NewTypeTranslation_SdnString.DiscardUnknown(m)
}

var xxx_messageInfo_P4NewTypeTranslation_SdnString proto.InternalMessageInfo

// New types introduced with the "type" keyword
type P4NewTypeSpec struct {
	// Types that are valid to be assigned to Representation:
	//	*P4NewTypeSpec_OriginalType
	//	*P4NewTypeSpec_TranslatedType
	Representation isP4NewTypeSpec_Representation `protobuf_oneof:"representation"`
	// for other annotations (not @p4runtime_translation)
	Annotations           []string                `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty"`
	StructuredAnnotations []*StructuredAnnotation `protobuf:"bytes,4,rep,name=structured_annotations,json=structuredAnnotations,proto3" json:"structured_annotations,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                `json:"-"`
	XXX_unrecognized      []byte                  `json:"-"`
	XXX_sizecache         int32                   `json:"-"`
}

func (m *P4NewTypeSpec) Reset()         { *m = P4NewTypeSpec{} }
func (m *P4NewTypeSpec) String() string { return proto.CompactTextString(m) }
func (*P4NewTypeSpec) ProtoMessage()    {}
func (*P4NewTypeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3b5328bffaabda, []int{24}
}

func (m *P4NewTypeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P4NewTypeSpec.Unmarshal(m, b)
}
func (m *P4NewTypeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P4NewTypeSpec.Marshal(b, m, deterministic)
}
func (m *P4NewTypeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P4NewTypeSpec.Merge(m, src)
}
func (m *P4NewTypeSpec) XXX_Size() int {
	return xxx_messageInfo_P4NewTypeSpec.Size(m)
}
func (m *P4NewTypeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_P4NewTypeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_P4NewTypeSpec proto.InternalMessageInfo

type isP4NewTypeSpec_Representation interface {
	isP4NewTypeSpec_Representation()
}

type P4NewTypeSpec_OriginalType struct {
	OriginalType *P4DataTypeSpec `protobuf:"bytes,1,opt,name=original_type,json=originalType,proto3,oneof"`
}

type P4NewTypeSpec_TranslatedType struct {
	TranslatedType *P4NewTypeTranslation `protobuf:"bytes,2,opt,name=translated_type,json=translatedType,proto3,oneof"`
}

func (*P4NewTypeSpec_OriginalType) isP4NewTypeSpec_Representation() {}

func (*P4NewTypeSpec_TranslatedType) isP4NewTypeSpec_Representation() {}

func (m *P4NewTypeSpec) GetRepresentation() isP4NewTypeSpec_Representation {
	if m != nil {
		return m.Representation
	}
	return nil
}

func (m *P4NewTypeSpec) GetOriginalType() *P4DataTypeSpec {
	if x, ok := m.GetRepresentation().(*P4NewTypeSpec_OriginalType); ok {
		return x.OriginalType
	}
	return nil
}

func (m *P4NewTypeSpec) GetTranslatedType() *P4NewTypeTranslation {
	if x, ok := m.GetRepresentation().(*P4NewTypeSpec_TranslatedType); ok {
		return x.TranslatedType
	}
	return nil
}

func (m *P4NewTypeSpec) GetAnnotations() []string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *P4NewTypeSpec) GetStructuredAnnotations() []*StructuredAnnotation {
	if m != nil {
		return m.StructuredAnnotations
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*P4NewTypeSpec) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*P4NewTypeSpec_OriginalType)(nil),
		(*P4NewTypeSpec_TranslatedType)(nil),
	}
}

func init() {
	proto.RegisterType((*P4TypeInfo)(nil), "p4.config.v1.P4TypeInfo")
	proto.RegisterMapType((map[string]*P4EnumTypeSpec)(nil), "p4.config.v1.P4TypeInfo.EnumsEntry")
	proto.RegisterMapType((map[string]*P4HeaderUnionTypeSpec)(nil), "p4.config.v1.P4TypeInfo.HeaderUnionsEntry")
	proto.RegisterMapType((map[string]*P4HeaderTypeSpec)(nil), "p4.config.v1.P4TypeInfo.HeadersEntry")
	proto.RegisterMapType((map[string]*P4NewTypeSpec)(nil), "p4.config.v1.P4TypeInfo.NewTypesEntry")
	proto.RegisterMapType((map[string]*P4SerializableEnumTypeSpec)(nil), "p4.config.v1.P4TypeInfo.SerializableEnumsEntry")
	proto.RegisterMapType((map[string]*P4StructTypeSpec)(nil), "p4.config.v1.P4TypeInfo.StructsEntry")
	proto.RegisterType((*P4DataTypeSpec)(nil), "p4.config.v1.P4DataTypeSpec")
	proto.RegisterType((*P4NamedType)(nil), "p4.config.v1.P4NamedType")
	proto.RegisterType((*P4BoolType)(nil), "p4.config.v1.P4BoolType")
	proto.RegisterType((*P4ErrorType)(nil), "p4.config.v1.P4ErrorType")
	proto.RegisterType((*P4BitstringLikeTypeSpec)(nil), "p4.config.v1.P4BitstringLikeTypeSpec")
	proto.RegisterType((*P4BitTypeSpec)(nil), "p4.config.v1.P4BitTypeSpec")
	proto.RegisterType((*P4IntTypeSpec)(nil), "p4.config.v1.P4IntTypeSpec")
	proto.RegisterType((*P4VarbitTypeSpec)(nil), "p4.config.v1.P4VarbitTypeSpec")
	proto.RegisterType((*P4TupleTypeSpec)(nil), "p4.config.v1.P4TupleTypeSpec")
	proto.RegisterType((*P4StructTypeSpec)(nil), "p4.config.v1.P4StructTypeSpec")
	proto.RegisterType((*P4StructTypeSpec_Member)(nil), "p4.config.v1.P4StructTypeSpec.Member")
	proto.RegisterType((*P4HeaderTypeSpec)(nil), "p4.config.v1.P4HeaderTypeSpec")
	proto.RegisterType((*P4HeaderTypeSpec_Member)(nil), "p4.config.v1.P4HeaderTypeSpec.Member")
	proto.RegisterType((*P4HeaderUnionTypeSpec)(nil), "p4.config.v1.P4HeaderUnionTypeSpec")
	proto.RegisterType((*P4HeaderUnionTypeSpec_Member)(nil), "p4.config.v1.P4HeaderUnionTypeSpec.Member")
	proto.RegisterType((*P4HeaderStackTypeSpec)(nil), "p4.config.v1.P4HeaderStackTypeSpec")
	proto.RegisterType((*P4HeaderUnionStackTypeSpec)(nil), "p4.config.v1.P4HeaderUnionStackTypeSpec")
	proto.RegisterType((*KeyValuePair)(nil), "p4.config.v1.KeyValuePair")
	proto.RegisterType((*KeyValuePairList)(nil), "p4.config.v1.KeyValuePairList")
	proto.RegisterType((*Expression)(nil), "p4.config.v1.Expression")
	proto.RegisterType((*ExpressionList)(nil), "p4.config.v1.ExpressionList")
	proto.RegisterType((*StructuredAnnotation)(nil), "p4.config.v1.StructuredAnnotation")
	proto.RegisterType((*P4EnumTypeSpec)(nil), "p4.config.v1.P4EnumTypeSpec")
	proto.RegisterType((*P4EnumTypeSpec_Member)(nil), "p4.config.v1.P4EnumTypeSpec.Member")
	proto.RegisterType((*P4SerializableEnumTypeSpec)(nil), "p4.config.v1.P4SerializableEnumTypeSpec")
	proto.RegisterType((*P4SerializableEnumTypeSpec_Member)(nil), "p4.config.v1.P4SerializableEnumTypeSpec.Member")
	proto.RegisterType((*P4ErrorTypeSpec)(nil), "p4.config.v1.P4ErrorTypeSpec")
	proto.RegisterType((*P4NewTypeTranslation)(nil), "p4.config.v1.P4NewTypeTranslation")
	proto.RegisterType((*P4NewTypeTranslation_SdnString)(nil), "p4.config.v1.P4NewTypeTranslation.SdnString")
	proto.RegisterType((*P4NewTypeSpec)(nil), "p4.config.v1.P4NewTypeSpec")
}

func init() { proto.RegisterFile("p4/config/v1/p4types.proto", fileDescriptor_2e3b5328bffaabda) }

var fileDescriptor_2e3b5328bffaabda = []byte{
	// 1451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0xdd, 0x6e, 0x13, 0x47,
	0x14, 0x8e, 0xed, 0xf8, 0xef, 0xd8, 0x49, 0xcc, 0x08, 0xe8, 0xd6, 0xf4, 0x27, 0x6c, 0x44, 0x15,
	0x41, 0x6b, 0x2b, 0x60, 0x10, 0xa0, 0x96, 0xaa, 0x86, 0xa8, 0x8e, 0x0a, 0x25, 0xda, 0x50, 0x4a,
	0xb9, 0xc0, 0x5d, 0xc7, 0x43, 0x32, 0x8a, 0x3d, 0xbb, 0xda, 0x9d, 0x35, 0x98, 0x8b, 0xbe, 0x47,
	0x9f, 0xa2, 0x52, 0xd5, 0x5e, 0xf7, 0x0d, 0xaa, 0xde, 0xf5, 0xa6, 0x97, 0xbd, 0xe8, 0x5b, 0xb4,
	0x9a, 0x99, 0xfd, 0x99, 0x5d, 0x8f, 0xed, 0x40, 0x2f, 0xb8, 0xca, 0x7a, 0xf6, 0x7c, 0xdf, 0x39,
	0x67, 0xce, 0xcc, 0x77, 0xce, 0x06, 0x9a, 0x6e, 0xa7, 0x7d, 0xe8, 0xd0, 0xe7, 0xe4, 0xa8, 0x3d,
	0xd9, 0x69, 0xbb, 0x1d, 0x36, 0x75, 0xb1, 0xdf, 0x72, 0x3d, 0x87, 0x39, 0xa8, 0xee, 0x76, 0x5a,
	0xf2, 0x5d, 0x6b, 0xb2, 0x63, 0xfe, 0x52, 0x01, 0xd8, 0xef, 0x3c, 0x9a, 0xba, 0x78, 0x8f, 0x3e,
	0x77, 0xd0, 0xe7, 0x50, 0xf6, 0x99, 0x17, 0x1c, 0x32, 0xdf, 0xc8, 0x6d, 0x16, 0xb6, 0x6b, 0x57,
	0x2f, 0xb5, 0x54, 0xf3, 0x56, 0x62, 0xda, 0x3a, 0x90, 0x76, 0xbb, 0x94, 0x79, 0x53, 0x2b, 0x42,
	0x71, 0x82, 0x63, 0x6c, 0x0f, 0xb1, 0xe7, 0x1b, 0xf9, 0x25, 0x04, 0x3d, 0x69, 0x17, 0x12, 0x84,
	0x28, 0xf4, 0x10, 0xd6, 0xe4, 0x63, 0x3f, 0xa0, 0xc4, 0xa1, 0xbe, 0x51, 0x10, 0x34, 0x97, 0x97,
	0xd0, 0x7c, 0x23, 0x8c, 0x25, 0x57, 0xfd, 0x58, 0x59, 0x42, 0xb7, 0xa0, 0x88, 0x69, 0x30, 0xf6,
	0x8d, 0x55, 0x41, 0xb4, 0x35, 0x97, 0x68, 0x97, 0x5b, 0x49, 0x06, 0x89, 0x40, 0xd7, 0xa0, 0x88,
	0x3d, 0xcf, 0xf1, 0x8c, 0xe2, 0x66, 0x6e, 0xbb, 0x76, 0xf5, 0xfd, 0x2c, 0x74, 0x97, 0xbf, 0xe4,
	0xf8, 0x03, 0x17, 0x1f, 0x5a, 0xd2, 0x16, 0x3d, 0x03, 0xe4, 0x63, 0x8f, 0xd8, 0x23, 0xf2, 0xca,
	0x1e, 0x8c, 0x70, 0x5f, 0x3a, 0x2f, 0x09, 0xe7, 0xed, 0xf9, 0xbb, 0xa9, 0x40, 0x94, 0x40, 0xce,
	0xf8, 0xd9, 0x75, 0x74, 0x17, 0xaa, 0x14, 0xbf, 0xe8, 0x8b, 0x92, 0x1a, 0x65, 0x41, 0xfb, 0xd1,
	0x5c, 0xda, 0xaf, 0xf1, 0x0b, 0xfe, 0x1c, 0xb2, 0x55, 0x68, 0xf8, 0xb3, 0xf9, 0x14, 0xea, 0x6a,
	0xfd, 0x50, 0x03, 0x0a, 0x27, 0x78, 0x6a, 0xe4, 0x36, 0x73, 0xdb, 0x55, 0x8b, 0x3f, 0xa2, 0x0e,
	0x14, 0x27, 0xf6, 0x28, 0xc0, 0x46, 0x5e, 0xe4, 0xfe, 0x41, 0xd6, 0x85, 0x84, 0x27, 0xc9, 0x0b,
	0xe3, 0xdb, 0xf9, 0x9b, 0x39, 0xce, 0xad, 0x96, 0xf6, 0x0d, 0xb8, 0x25, 0x5c, 0xc7, 0x3d, 0x84,
	0x33, 0x33, 0xf5, 0xd6, 0x38, 0xb8, 0x95, 0x76, 0xb0, 0xa5, 0x77, 0x20, 0x38, 0x74, 0x5e, 0x1e,
	0x03, 0x24, 0x35, 0xd0, 0xd0, 0x5f, 0x4d, 0xd3, 0xbf, 0x37, 0x73, 0x2e, 0x68, 0x30, 0xd6, 0xf1,
	0x52, 0x38, 0xaf, 0xaf, 0xb3, 0xc6, 0xc7, 0x9d, 0xb4, 0x8f, 0xed, 0x99, 0xfd, 0xcf, 0x10, 0xe9,
	0xfc, 0x3d, 0x81, 0xb5, 0xd4, 0x01, 0xd0, 0xb8, 0xd9, 0x49, 0xbb, 0xb9, 0x90, 0x75, 0x13, 0xe2,
	0x33, 0xcc, 0xe6, 0xbf, 0x45, 0x58, 0xdf, 0xef, 0xdc, 0xb3, 0x99, 0x1d, 0xbd, 0x45, 0xbb, 0x50,
	0x1d, 0x10, 0xe6, 0x33, 0x8f, 0xd0, 0x23, 0xe1, 0x41, 0x73, 0xf7, 0xbb, 0x91, 0xc1, 0x7d, 0x72,
	0x82, 0x23, 0x64, 0x6f, 0xc5, 0x4a, 0x90, 0xa8, 0x05, 0xab, 0x03, 0xc7, 0x19, 0x85, 0xf1, 0x18,
	0x33, 0x0c, 0x8e, 0x33, 0xe2, 0xc0, 0xde, 0x8a, 0x25, 0xec, 0xd0, 0x75, 0x28, 0xb2, 0xc0, 0x1d,
	0x61, 0xa3, 0xa0, 0xbf, 0xa3, 0x8f, 0xf8, 0x4b, 0xc5, 0x95, 0xb4, 0x46, 0xd7, 0xa0, 0x24, 0x25,
	0xcb, 0x58, 0x15, 0xb8, 0x77, 0x67, 0x12, 0xb7, 0xc7, 0x78, 0x18, 0x7a, 0x0a, 0x4d, 0x39, 0x48,
	0x4a, 0x4b, 0x28, 0x08, 0x8b, 0x41, 0xd2, 0x14, 0xdd, 0x81, 0xba, 0x2a, 0x68, 0x46, 0x69, 0x39,
	0xb4, 0xa6, 0x08, 0x18, 0xea, 0xc5, 0x78, 0x9f, 0xd9, 0x87, 0x27, 0x46, 0x79, 0xd1, 0x91, 0x3e,
	0xe0, 0x26, 0x4a, 0xb6, 0x21, 0x93, 0x58, 0x46, 0x4f, 0x00, 0xa9, 0x91, 0x84, 0x7c, 0x15, 0xfd,
	0xf9, 0x52, 0xae, 0x48, 0x96, 0xb4, 0x71, 0x9c, 0x79, 0x87, 0xda, 0xb0, 0xca, 0x65, 0xce, 0xa8,
	0x2e, 0xcf, 0x4d, 0x18, 0xf2, 0x63, 0x27, 0x95, 0x15, 0xf4, 0x88, 0x58, 0x59, 0x79, 0xc5, 0xa4,
	0xae, 0xf6, 0xe0, 0xcc, 0x8c, 0xae, 0x1a, 0xb5, 0xe5, 0x0e, 0x1b, 0x59, 0x09, 0x45, 0x37, 0xa0,
	0x12, 0x29, 0xa8, 0x51, 0x5f, 0x4e, 0x50, 0x0e, 0x55, 0xb3, 0x5b, 0x83, 0x2a, 0xc7, 0xf4, 0x7d,
	0x17, 0x1f, 0x9a, 0x17, 0xa1, 0xa6, 0x98, 0x21, 0x04, 0xab, 0xd4, 0x1e, 0xe3, 0xf0, 0x6a, 0x89,
	0x67, 0xb3, 0xce, 0x5b, 0x6b, 0x74, 0x60, 0xcd, 0x35, 0x0e, 0x88, 0xf3, 0x32, 0xff, 0xce, 0xc1,
	0x3b, 0x73, 0x2e, 0x04, 0x6a, 0x43, 0x61, 0x40, 0x58, 0x78, 0x89, 0x2e, 0x68, 0x2e, 0x91, 0x52,
	0x0c, 0x6e, 0xc9, 0x01, 0x84, 0xb2, 0x79, 0x77, 0x78, 0x8f, 0xa6, 0x00, 0x84, 0x32, 0x74, 0x13,
	0x4a, 0x13, 0xdb, 0xe3, 0x4e, 0x0a, 0x7a, 0x09, 0x7e, 0x2c, 0xde, 0x2a, 0xb0, 0xd0, 0x1e, 0x6d,
	0x42, 0xcd, 0xa6, 0xd4, 0x61, 0x36, 0x13, 0xdd, 0x99, 0x37, 0xd5, 0xaa, 0xa5, 0x2e, 0xa5, 0xb7,
	0xe9, 0x0a, 0xac, 0xa5, 0x22, 0x46, 0x4d, 0xa8, 0x0c, 0x08, 0x7b, 0x41, 0x86, 0xec, 0x58, 0x24,
	0x58, 0xb4, 0xe2, 0xdf, 0xd2, 0x58, 0x89, 0x76, 0xa1, 0xf1, 0x75, 0x68, 0x64, 0xc3, 0x44, 0x17,
	0xa1, 0x3e, 0xb6, 0x5f, 0xf6, 0x33, 0x98, 0xda, 0xd8, 0x7e, 0xd9, 0x8d, 0x60, 0x7b, 0xb0, 0x91,
	0x11, 0x05, 0x74, 0x03, 0xca, 0x63, 0x3c, 0x1e, 0xf0, 0x99, 0x45, 0x0e, 0x3d, 0x33, 0x82, 0xae,
	0x0a, 0x9d, 0x15, 0x19, 0x9b, 0xbf, 0xe7, 0x78, 0x08, 0xe9, 0x46, 0xc8, 0x07, 0xa0, 0x34, 0xd9,
	0xa5, 0xc5, 0x9d, 0xb3, 0xf5, 0x40, 0x58, 0xc7, 0xac, 0xd9, 0x0d, 0xce, 0xcf, 0x6c, 0x70, 0xf3,
	0x5b, 0x28, 0x49, 0x90, 0xee, 0xd4, 0xa1, 0x5b, 0xca, 0xf6, 0xcf, 0x6b, 0x50, 0xa9, 0x7c, 0x2a,
	0x2c, 0x7c, 0x32, 0xff, 0x14, 0x09, 0xa5, 0xbb, 0xef, 0x29, 0x12, 0x4a, 0x03, 0xde, 0x20, 0xa1,
	0xef, 0x17, 0x26, 0xd4, 0x9d, 0x4d, 0xe8, 0x74, 0x8d, 0x45, 0xc9, 0xec, 0x8f, 0x1c, 0x9c, 0xd3,
	0xb6, 0x7d, 0x74, 0x2f, 0x9b, 0xde, 0xe5, 0x53, 0x0c, 0x0b, 0x6f, 0x90, 0xe3, 0xc3, 0x85, 0x39,
	0xee, 0xc4, 0x9d, 0x25, 0xbf, 0x44, 0x90, 0xa2, 0xbe, 0x62, 0x3e, 0x4b, 0x32, 0x4a, 0x09, 0xb4,
	0xc2, 0x95, 0x3b, 0x25, 0x17, 0x0f, 0xc9, 0x27, 0xaf, 0xe4, 0x10, 0x50, 0xb4, 0xc4, 0xb3, 0x49,
	0xa1, 0x39, 0xbf, 0x0b, 0xa0, 0x4f, 0x33, 0x5d, 0x6d, 0xa9, 0xab, 0x54, 0x4f, 0xd3, 0xf9, 0xdb,
	0x87, 0xfa, 0x57, 0x78, 0xfa, 0x98, 0x8f, 0x18, 0xfb, 0x36, 0xf1, 0x34, 0xb3, 0x4a, 0x2b, 0x3d,
	0xab, 0x64, 0x66, 0x83, 0xdd, 0x97, 0xae, 0x87, 0x7d, 0x9f, 0x38, 0x34, 0x1c, 0x54, 0xcc, 0x3d,
	0x68, 0xa8, 0x8c, 0xf7, 0x89, 0xcf, 0xd0, 0x75, 0xa8, 0x9c, 0x4c, 0xfa, 0xae, 0x4d, 0xe2, 0x7a,
	0x37, 0xd3, 0x34, 0x2a, 0xc2, 0x2a, 0x9f, 0x4c, 0xf8, 0x5f, 0xdf, 0xfc, 0x01, 0x20, 0xe1, 0x47,
	0x5b, 0x50, 0x97, 0xa7, 0xad, 0x2f, 0xe3, 0x11, 0x31, 0xf2, 0x6e, 0x2b, 0x57, 0x05, 0x1e, 0x5d,
	0x84, 0x1a, 0xa1, 0xec, 0x46, 0xa7, 0x9f, 0xc4, 0x5c, 0xe8, 0xad, 0x58, 0x20, 0x16, 0xa5, 0xc9,
	0x87, 0x00, 0x7c, 0x86, 0x09, 0x2d, 0xb8, 0x12, 0x57, 0xc4, 0x30, 0xe4, 0x38, 0x23, 0x61, 0xd0,
	0x2d, 0x87, 0x19, 0x9b, 0xf7, 0x61, 0x3d, 0xf1, 0x2f, 0x12, 0xb9, 0x0d, 0x35, 0x1c, 0xaf, 0x44,
	0xb9, 0xcc, 0xdf, 0x12, 0xd5, 0xd8, 0xfc, 0x2d, 0x07, 0x67, 0xa5, 0x0a, 0x05, 0x1e, 0x1e, 0x7e,
	0x11, 0x9f, 0x52, 0xed, 0xd1, 0xfc, 0x12, 0x36, 0x12, 0x6c, 0x7f, 0x44, 0x7c, 0xa6, 0x57, 0x95,
	0x74, 0x7c, 0xbd, 0x15, 0x6b, 0x1d, 0xa7, 0x23, 0xee, 0x42, 0x3d, 0xdc, 0x7a, 0xc9, 0xa2, 0xed,
	0x3c, 0xd9, 0x82, 0xf1, 0x1d, 0x93, 0x45, 0xe0, 0xbf, 0xba, 0x25, 0x3e, 0x1d, 0x0e, 0xa7, 0xe6,
	0x3f, 0x79, 0x3e, 0x7f, 0xaa, 0x73, 0x2f, 0xfa, 0x2c, 0x7b, 0x91, 0xb7, 0x16, 0x8d, 0xe5, 0xaf,
	0x7f, 0x83, 0xd1, 0x77, 0x70, 0xde, 0x8f, 0x37, 0xad, 0xaf, 0x1a, 0xcb, 0x4f, 0x54, 0x33, 0xed,
	0x4f, 0xb7, 0xc1, 0xd6, 0x39, 0x5f, 0xb3, 0xea, 0x37, 0x7f, 0xcc, 0x2d, 0x54, 0x87, 0xb7, 0x19,
	0x9b, 0xf9, 0x57, 0x81, 0x0b, 0xc1, 0xbc, 0xcf, 0x0d, 0x74, 0x0f, 0x36, 0x02, 0x3a, 0xc4, 0xde,
	0x68, 0xca, 0xef, 0x83, 0x98, 0xa9, 0x96, 0xcf, 0x2d, 0xd6, 0x7a, 0x82, 0x11, 0xe3, 0xd3, 0x5e,
	0x52, 0xbc, 0xbc, 0xfe, 0x4b, 0x79, 0x5e, 0x00, 0xcb, 0x0a, 0x59, 0x78, 0x9d, 0xcd, 0x5a, 0xfd,
	0xbf, 0x85, 0xfc, 0x69, 0x71, 0x21, 0xcf, 0xaa, 0x0a, 0x56, 0x0f, 0x75, 0xea, 0xad, 0x46, 0x6c,
	0x5e, 0xe1, 0xf3, 0x50, 0xea, 0x1f, 0x19, 0xc8, 0x48, 0xdf, 0xa4, 0x6a, 0x32, 0xf1, 0xfc, 0x9a,
	0x83, 0xb3, 0xf1, 0x37, 0xe1, 0x23, 0xcf, 0xa6, 0xfe, 0x48, 0x0a, 0x47, 0x03, 0x0a, 0x81, 0x47,
	0x22, 0xb1, 0x0e, 0x3c, 0x22, 0x34, 0x72, 0x48, 0x93, 0x51, 0x4c, 0x48, 0xbd, 0xd0, 0xc8, 0x21,
	0x8d, 0x86, 0x31, 0xf4, 0x00, 0x80, 0x1b, 0x85, 0x1f, 0x8d, 0x52, 0x10, 0x3e, 0x9e, 0xf3, 0x09,
	0xaa, 0xb8, 0x6b, 0x1d, 0x0c, 0xe9, 0x81, 0xc0, 0x70, 0xb9, 0xf4, 0xa3, 0x1f, 0xcd, 0x1a, 0x54,
	0xe3, 0x37, 0x5d, 0x80, 0x0a, 0xe7, 0xe6, 0x27, 0xd2, 0xfc, 0x39, 0xcf, 0x27, 0x4b, 0xe5, 0x5b,
	0x16, 0xdd, 0x85, 0x35, 0xc7, 0x23, 0x47, 0x84, 0xda, 0x23, 0xf5, 0xd0, 0x2e, 0x9c, 0x94, 0x7a,
	0x2b, 0x56, 0x3d, 0x02, 0x89, 0x53, 0xfb, 0x00, 0x36, 0x58, 0x18, 0x15, 0x1e, 0x4a, 0x1a, 0x29,
	0x8d, 0xe6, 0xf2, 0x1c, 0xb8, 0x40, 0x26, 0x60, 0x41, 0xf7, 0x36, 0xcf, 0x41, 0xb7, 0x01, 0xeb,
	0x1e, 0xe6, 0x7a, 0x8d, 0xa9, 0x5c, 0xea, 0x7e, 0xf2, 0xf4, 0xca, 0x11, 0x61, 0xc7, 0xc1, 0xa0,
	0x75, 0xe8, 0x8c, 0xdb, 0x6e, 0x67, 0x64, 0xd3, 0xa3, 0xb6, 0xdb, 0xf1, 0x02, 0xca, 0xc8, 0x18,
	0xb7, 0x8f, 0x9c, 0xb6, 0xfa, 0x5f, 0xc6, 0x41, 0x49, 0xfc, 0x7b, 0xf1, 0xda, 0x7f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xdb, 0x6b, 0x54, 0xd0, 0x7c, 0x14, 0x00, 0x00,
}
