services:
  - docker

# Github token
env:
  - secure: "kgFEYWugXGaFM/cEh3xUImFcbaq3nFcHT4P9G1XmiJ5JjpT7+5NkvCLydYKEBPEQuIVH+DRxrK1LqySWHC2qhBHE/AyB/0hpQ6JsYOL6LKPzPYUwSJhFKFHxxP1OtBrS5f51DUQ5wCPI6gF6sQP2l24QIVjIfgh3FSkpXX7RzUFF2eC2MS3Tg/NljsD5kGqCGdzaguaFculUuPpRqNixqZZXiM2BjDHHwGWT2rH7NcP4u6x2ycaTcUfN/XnnfDTrIkunicYte/x+l0QOMNXRZ3L/gs1Wgia4UT28P6Bld3MPVUa3sJe+Nz3eqDBZ/I8nyIm7tEvM3oNjLjT5i4JjDWQYffRkc2upVDim4d1boCbx+6zGBrKjP/IJ0AoqG0IBEKaYqfJkHEB8o2mKgp+ib8am69M3Ap3QAPjHGCmlix13+2IHsevoWw/dFnjP8ipb8YTOX/R9xV9cKLiTp4mrcGbDrPUJoadQ2RghNRcqBroS463pPZTsi/9UxcfHGMSWdDv7dqJJw/Y/fPT9mqBBpvX7+Mw2NKNB4AsC+ZCMWVP2kw36LuTww6mjpNy6NgfoctcNqB9rfMnyRKWDAfK4EaFfR5tx6P8xlupNqSnzqTqQzqCDrsTrFyXIXSLGqulz1ZC+RucM0jkCMcjpS+EsFxLUexAgZLl59/bHPEakIvo="

install:
  - docker build -t p4runtime-ci -f CI/Dockerfile .

# We check that the P4Runtime Protobuf files are correct (by compiling them with
# protoc), then we generate the HTML for the spec.
script:
  - docker run -t p4runtime-ci /p4runtime/CI/compile_protos.sh /tmp/ || travis_terminate 1
  - docker run -v `pwd`/docs/v1:/usr/src/p4-spec p4lang/p4rt-madoko:latest make || travis_terminate 1
  - ./tools/madokolint.py docs/v1/P4Runtime-Spec.mdk

after_success:
  - ls docs/v1/build

deploy:
  - provider: s3
    access_key_id: AKIAIT3MAUFCQEY7KAFQ
    secret_access_key:
      secure: O1tX0ymUh2sX3t+N0IYKbFasvAVsOxJZ3OyIi5M/6m5IHsDJUS3ldtHGVCAMD+dJEiSbcaxYdXfnxNlO8IFCH60eF4Q4STKmKn7jqjSRpAwf/97HPfI1M97RhMBFbqD0LM8nLQtAhQT5VVQQNcOl49LHZqMEDVtfA6Ta4noLXh32aawEq5DS+jI4iXBhk6CNfTTSs8GeSJmXIxJcoOmMkH6ibg3ZJ1mOV0F66IVqLyVoGhCgS4uwY9v7YmWJ4LRQDM3fycx08awlosFrzwOKrZp2fgTIzXAFd2ndL2OXzhCj+2p5Lp/LM6gIG/QQVHPnOPDs8ZxsKYOrycsPlJHs+3j+Wjy6a0RutZuLUXC2uHxuK/ZFQ+gJ1ExePzFRS83IESgG4swd9fGa9vBeWaP/RbS3KCc2LWLBsQf7MMIN+8tWLqul9k3yuUwaANOnE3Lt6bw6nKW5sef4ULqHkMO4ZH/S6a+TLeoKqDh59d4KpS/K2YPXediEBWk2Jk5bI5JHZDDFbde0Kls3cXOj3b6DTfMUQ4zcgDqVpyNKfOU764FnOGThVt9+zU6vIXRr6Y9olumgC24sz8IeEVEJv5234sdNd4E11B8tQE9JjoQDzmLgJ+xHNan0b1RgW/watYW2JFixwgYu2RLvHGMNySj9kw5t8Mj2Olj0FtsOq9MRHNE=
    bucket: p4runtime
    local-dir: docs/v1/build
    upload-dir: travis/$TRAVIS_BRANCH
    acl: public_read
    region: us-west-2
    skip_cleanup: true
    on:
      repo: p4lang/p4runtime
      all_branches: true
  - provider: s3
    access_key_id: AKIAIT3MAUFCQEY7KAFQ
    secret_access_key:
      secure: O1tX0ymUh2sX3t+N0IYKbFasvAVsOxJZ3OyIi5M/6m5IHsDJUS3ldtHGVCAMD+dJEiSbcaxYdXfnxNlO8IFCH60eF4Q4STKmKn7jqjSRpAwf/97HPfI1M97RhMBFbqD0LM8nLQtAhQT5VVQQNcOl49LHZqMEDVtfA6Ta4noLXh32aawEq5DS+jI4iXBhk6CNfTTSs8GeSJmXIxJcoOmMkH6ibg3ZJ1mOV0F66IVqLyVoGhCgS4uwY9v7YmWJ4LRQDM3fycx08awlosFrzwOKrZp2fgTIzXAFd2ndL2OXzhCj+2p5Lp/LM6gIG/QQVHPnOPDs8ZxsKYOrycsPlJHs+3j+Wjy6a0RutZuLUXC2uHxuK/ZFQ+gJ1ExePzFRS83IESgG4swd9fGa9vBeWaP/RbS3KCc2LWLBsQf7MMIN+8tWLqul9k3yuUwaANOnE3Lt6bw6nKW5sef4ULqHkMO4ZH/S6a+TLeoKqDh59d4KpS/K2YPXediEBWk2Jk5bI5JHZDDFbde0Kls3cXOj3b6DTfMUQ4zcgDqVpyNKfOU764FnOGThVt9+zU6vIXRr6Y9olumgC24sz8IeEVEJv5234sdNd4E11B8tQE9JjoQDzmLgJ+xHNan0b1RgW/watYW2JFixwgYu2RLvHGMNySj9kw5t8Mj2Olj0FtsOq9MRHNE=
    bucket: p4runtime
    local-dir: docs/v1/build
    upload-dir: docs/master
    acl: public_read
    region: us-west-2
    skip_cleanup: true
    on:
      repo: p4lang/p4runtime
      branch: master
  - provider: s3
    access_key_id: AKIAIT3MAUFCQEY7KAFQ
    secret_access_key:
      secure: O1tX0ymUh2sX3t+N0IYKbFasvAVsOxJZ3OyIi5M/6m5IHsDJUS3ldtHGVCAMD+dJEiSbcaxYdXfnxNlO8IFCH60eF4Q4STKmKn7jqjSRpAwf/97HPfI1M97RhMBFbqD0LM8nLQtAhQT5VVQQNcOl49LHZqMEDVtfA6Ta4noLXh32aawEq5DS+jI4iXBhk6CNfTTSs8GeSJmXIxJcoOmMkH6ibg3ZJ1mOV0F66IVqLyVoGhCgS4uwY9v7YmWJ4LRQDM3fycx08awlosFrzwOKrZp2fgTIzXAFd2ndL2OXzhCj+2p5Lp/LM6gIG/QQVHPnOPDs8ZxsKYOrycsPlJHs+3j+Wjy6a0RutZuLUXC2uHxuK/ZFQ+gJ1ExePzFRS83IESgG4swd9fGa9vBeWaP/RbS3KCc2LWLBsQf7MMIN+8tWLqul9k3yuUwaANOnE3Lt6bw6nKW5sef4ULqHkMO4ZH/S6a+TLeoKqDh59d4KpS/K2YPXediEBWk2Jk5bI5JHZDDFbde0Kls3cXOj3b6DTfMUQ4zcgDqVpyNKfOU764FnOGThVt9+zU6vIXRr6Y9olumgC24sz8IeEVEJv5234sdNd4E11B8tQE9JjoQDzmLgJ+xHNan0b1RgW/watYW2JFixwgYu2RLvHGMNySj9kw5t8Mj2Olj0FtsOq9MRHNE=
    bucket: p4runtime
    local-dir: docs/v1/build
    upload-dir: docs/$TRAVIS_TAG
    acl: public_read
    region: us-west-2
    skip_cleanup: true
    on:
      repo: p4lang/p4runtime
      tags: true
  - provider: script
    script: bash CI/deploy.sh $TRAVIS_TAG
    skip_cleanup: true
    on:
      repo: p4lang/p4runtime
      tags: true
  - provider: script
    script: bash CI/deploy.sh master
    skip_cleanup: true
    on:
      repo: p4lang/p4runtime
      branch: master
