name: Any branch uploads

on:
  push:
    branches:
      - '**'

jobs:
  any-branch-uploads:
    if: ${{ github.repository == 'p4lang/p4runtime' }}
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Build spec
      run: |
        docker run -v `pwd`/docs/v1:/usr/src/p4-spec p4lang/p4rt-madoko:latest make
        ls docs/v1/build
    - name: Upload spec to S3 if needed
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'p4runtime'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'docs/v1/build'
        DEST_DIR: ci/${{ github.ref_name }} # only runs for push events
