# SPDX-FileCopyrightText: 2022 Antonin Bas
#
# SPDX-License-Identifier: Apache-2.0

name: Build spec

on:
  push:
    branches:
      - main
      - '*-dev'
  pull_request:
    branches:
      - main
      - '*-dev'

jobs:
  verify-licenses:
    runs-on: ubuntu-latest
    name: Validate that all files have copyright and license info
    steps:
      - uses: actions/checkout@v6
      - name: Install dev dependencies
        run: |
          ./CI/install-uv.sh
      - name: Validate presence of copyright and license info (python w/reuse)
        run: |
          uvx reuse lint

  asciidoc-lint:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Run linter
      run: |
        ./tools/asciidoclint.py docs/v1/P4Runtime-Spec.adoc

  build-spec:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Build spec
      run: |
        make -C docs/tools/
        docker run -v `pwd`/docs/v1:/usr/src/p4-spec p4lang/p4rt-asciidoc make build_spec_with_images
        ls docs/v1/build
