# SPDX-FileCopyrightText: 2026 The P4 Language Consortium
#
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.16)
project(p4runtime_consumer LANGUAGES NONE)
if(NOT COMPONENT STREQUAL "schemas")
  enable_language(CXX)
endif()
if(P4RUNTIME_SOURCE_DIR)
  if(NOT COMPONENT STREQUAL "schemas")
    # Dependencies supplied by a parent must be reused.
    find_package(Protobuf REQUIRED)
    set(P4RUNTIME_BUILD_CPP ON)
  endif()
  if(COMPONENT STREQUAL "grpc")
    find_package(gRPC CONFIG REQUIRED)
    set(P4RUNTIME_BUILD_GRPC ON)
  endif()
  add_subdirectory("${P4RUNTIME_SOURCE_DIR}" p4runtime)
  if(P4RUNTIME_INSTALL)
    message(FATAL_ERROR "Subproject installation should default to OFF")
  endif()
  set(p4runtime_PROTO_DIR "${P4RUNTIME_SOURCE_DIR}/proto")
else()
  find_package(p4runtime 1.6 CONFIG REQUIRED COMPONENTS ${COMPONENT})
endif()
foreach(schema google/rpc/status.proto p4/config/v1/p4info.proto
               p4/config/v1/p4types.proto p4/v1/p4runtime.proto p4/v1/p4data.proto)
  if(NOT EXISTS "${p4runtime_PROTO_DIR}/${schema}")
    message(FATAL_ERROR "Missing installed schema: ${schema}")
  endif()
endforeach()
if(NOT TARGET p4runtime::schemas)
  message(FATAL_ERROR "Missing schema target")
endif()
if(NOT COMPONENT STREQUAL "schemas")
  add_executable(consumer main.cpp)
  target_link_libraries(consumer PRIVATE p4runtime::${COMPONENT})
  if(COMPONENT STREQUAL "grpc")
    target_compile_definitions(consumer PRIVATE TEST_GRPC)
  endif()
  enable_testing()
  add_test(NAME consumer COMMAND consumer)
endif()
